cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m3Discrtk2/Omega1 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m3Discrtk2/Omega0 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m3Discrtk2/Omega2 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m3Discrtk2/Omega10 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m0/Omega1 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m0/Omega0 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m0/Omega2 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m0/Omega10 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m8a/Omega1 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m3Discrtk3/Omega1 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m3Discrtk3/Omega0 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m3Discrtk3/Omega2 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m3Discrtk3/Omega10 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m8/Omega1 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m8/Omega0 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m8/Omega2 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m8/Omega10 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m2Selection/Omega1 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m2Selection/Omega0 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m2Selection/Omega2 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m2Selection/Omega10 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m1Neutral/Omega1 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m1Neutral/Omega0 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m1Neutral/Omega2 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m1Neutral/Omega10 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m7/Omega1 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m7/Omega0 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m7/Omega2 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim/m7/Omega10 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_ZygFili/modelAnull/Omega1 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_ZygFili/modelA/Omega1 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_ZygFili/modelA/Omega0 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_ZygFili/modelA/Omega2 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_ZygFili/modelA/Omega10 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_IncMasc/modelAnull/Omega1 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_IncMasc/modelA/Omega1 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_IncMasc/modelA/Omega0 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_IncMasc/modelA/Omega2 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_IncMasc/modelA/Omega10 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_NemSwae/modelAnull/Omega1 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_NemSwae/modelA/Omega1 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_NemSwae/modelA/Omega0 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_NemSwae/modelA/Omega2 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_NemSwae/modelA/Omega10 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_sesiidae/modelAnull/Omega1 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_sesiidae/modelA/Omega1 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_sesiidae/modelA/Omega0 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_sesiidae/modelA/Omega2 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_sesiidae/modelA/Omega10 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_papilionoidea/modelAnull/Omega1 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_papilionoidea/modelA/Omega1 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_papilionoidea/modelA/Omega0 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_papilionoidea/modelA/Omega2 && codeml
cd lep_blue_nucl_aln_trim/lep_blue_nucl_aln_trim_papilionoidea/modelA/Omega10 && codeml