cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_EucMixx/modelAnull/Omega1 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_EucMixx/modelA/Omega1 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_EucMixx/modelA/Omega0 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_EucMixx/modelA/Omega2 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_EucMixx/modelA/Omega10 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m3Discrtk2/Omega1 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m3Discrtk2/Omega0 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m3Discrtk2/Omega2 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m3Discrtk2/Omega10 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m0/Omega1 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m0/Omega0 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m0/Omega2 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m0/Omega10 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m8a/Omega1 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m3Discrtk3/Omega1 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m3Discrtk3/Omega0 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m3Discrtk3/Omega2 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m3Discrtk3/Omega10 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m8/Omega1 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m8/Omega0 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m8/Omega2 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m8/Omega10 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m2Selection/Omega1 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m2Selection/Omega0 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m2Selection/Omega2 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m2Selection/Omega10 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m1Neutral/Omega1 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m1Neutral/Omega0 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m1Neutral/Omega2 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m1Neutral/Omega10 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m7/Omega1 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m7/Omega0 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m7/Omega2 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename/m7/Omega10 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_NemSwae/modelAnull/Omega1 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_NemSwae/modelA/Omega1 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_NemSwae/modelA/Omega0 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_NemSwae/modelA/Omega2 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_NemSwae/modelA/Omega10 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_sesiidae/modelAnull/Omega1 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_sesiidae/modelA/Omega1 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_sesiidae/modelA/Omega0 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_sesiidae/modelA/Omega2 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_sesiidae/modelA/Omega10 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_ZygFili/modelAnull/Omega1 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_ZygFili/modelA/Omega1 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_ZygFili/modelA/Omega0 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_ZygFili/modelA/Omega2 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_ZygFili/modelA/Omega10 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_IncMasc/modelAnull/Omega1 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_IncMasc/modelA/Omega1 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_IncMasc/modelA/Omega0 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_IncMasc/modelA/Omega2 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_IncMasc/modelA/Omega10 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_papilionoidea/modelAnull/Omega1 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_papilionoidea/modelA/Omega1 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_papilionoidea/modelA/Omega0 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_papilionoidea/modelA/Omega2 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_papilionoidea/modelA/Omega10 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_microterigidae/modelAnull/Omega1 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_microterigidae/modelA/Omega1 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_microterigidae/modelA/Omega0 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_microterigidae/modelA/Omega2 && codeml
cd lep_UV_nucl_aln_trim_rename/lep_UV_nucl_aln_trim_rename_microterigidae/modelA/Omega10 && codeml